apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pcg.fullname" . }}-pcgignore
  labels:
    {{- include "pcg.labels" . | nindent 4 }}
data:
  .pcgignore: |
    {{- .Values.pcgignore | nindent 4 }}
