{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pcg.apiFullname" . }}
  labels:
    {{- include "pcg.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  podSelector:
    matchLabels:
      {{- include "pcg.apiSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        {{- if .Values.observability.prometheus.enabled }}
        - protocol: TCP
          port: {{ .Values.observability.prometheus.port }}
        {{- end }}
  egress:
    - {}
---
{{- if .Values.repoSync.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pcg.ingesterHeadlessServiceName" . }}
  labels:
    {{- include "pcg.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingester
spec:
  podSelector:
    matchLabels:
      {{- include "pcg.ingesterSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.observability.prometheus.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.observability.prometheus.port }}
    {{- else }}
    []
    {{- end }}
  egress:
    - {}
{{- end }}
---
{{- if .Values.resolutionEngine.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pcg.resolutionEngineFullname" . }}
  labels:
    {{- include "pcg.labels" . | nindent 4 }}
    app.kubernetes.io/component: resolution-engine
spec:
  podSelector:
    matchLabels:
      {{- include "pcg.resolutionEngineSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.observability.prometheus.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.observability.prometheus.port }}
    {{- else }}
    []
    {{- end }}
  egress:
    - {}
{{- end }}
{{- end }}
