{{- if .Values.repoSync.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pcg.ingestorFullname" . }}
  labels:
    {{- include "pcg.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestor
spec:
  clusterIP: None
  selector:
    {{- include "pcg.ingestorSelectorLabels" . | nindent 4 }}
  ports:
    - name: noop
      port: 80
      targetPort: 80
      protocol: TCP
{{- end }}
