apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-context-graph
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-example.yaml
  - service.yaml
  - statefulset.yaml
