@Library('controller-pipelines@main') _

def automationRepo = 'https://github.com/platformcontext/automation-configs.git'

pipeline {
  agent any

  stages {
    stage('Deploy') {
      steps {
        script {
          pipelineDeploy()
          echo "Using ${automationRepo}"
          sh './scripts/deploy.sh'
        }
      }
    }
  }
}
